# Quest 3

In [2]:
import pandas as pd

## 1) Load the JSON file that you created in the previous exercise into a dataframe

* set CarNumber as the index column

In [3]:
src_file =  "../ex02/auto.json"
df = pd.read_json(src_file)
df.set_index("CarNumber", inplace=True)
display(df)

              Refund     Fines    Make    Model
CarNumber
Y163O8161RUS       2   3200.00    Ford    Focus
E432XX77RUS        1   6500.00  Toyota    Camry
7184TT36RUS        1   2100.00    Ford    Focus
X582HE161RUS       2   2000.00    Ford    Focus
92918M178RUS       1   5700.00    Ford    Focus
...              ...       ...     ...      ...
Y163O8161RUS       2   1600.00    Ford    Focus
M0309X197RUS       1  22300.00    Ford    Focus
O673E8197RUS       2    600.00    Ford    Focus
8610T8154RUS       1   2000.00    Ford    Focus
H419XE197RUS       2   8594.59  Toyota  Corolla

[725 rows x 4 columns]

## 2) Make the following selects

* display the rows only where the __fines__ are more than 2,100

In [4]:
display(df[df["Fines"] > 2100])

              Refund     Fines        Make    Model
CarNumber
Y163O8161RUS       2   3200.00        Ford    Focus
E432XX77RUS        1   6500.00      Toyota    Camry
92918M178RUS       1   5700.00        Ford    Focus
H234YH197RUS       2   6000.00        Ford    Focus
E40577152RUS       1   8594.59        Ford    Focus
...              ...       ...         ...      ...
O718MM163RUS       2   8594.59        Ford    Focus
7065C8197RUS       2  11400.00  Volkswagen   Passat
O22097197RUS       1  24300.00        Ford    Focus
M0309X197RUS       1  22300.00        Ford    Focus
H419XE197RUS       2   8594.59      Toyota  Corolla

[455 rows x 4 columns]

* display the rows only where the __fines__ are more than 2,100 and the __refund__ equals 2

In [5]:
display(df[(df["Fines"] > 2100) & (df["Refund"] == 2)])

              Refund     Fines        Make    Model
CarNumber
Y163O8161RUS       2   3200.00        Ford    Focus
H234YH197RUS       2   6000.00        Ford    Focus
707987163RUS       2   2200.00        Ford    Focus
K330T8197RUS       2   8200.00       Skoda  Octavia
M592CH197RUS       2   8594.59       Skoda  Octavia
...              ...       ...         ...      ...
O136HO197RUS       2   7800.00      Toyota  Corolla
O68897197RUS       2  12300.00        Ford    Focus
O718MM163RUS       2   8594.59        Ford    Focus
7065C8197RUS       2  11400.00  Volkswagen   Passat
H419XE197RUS       2   8594.59      Toyota  Corolla

[309 rows x 4 columns]

* display the rows only where the __models__ are from the list: [’Focus’, ’Corolla’]

In [6]:
display(df[df["Model"].isin(["Focus", "Corolla"])])

              Refund     Fines    Make    Model
CarNumber
Y163O8161RUS       2   3200.00    Ford    Focus
7184TT36RUS        1   2100.00    Ford    Focus
X582HE161RUS       2   2000.00    Ford    Focus
92918M178RUS       1   5700.00    Ford    Focus
H234YH197RUS       2   6000.00    Ford    Focus
...              ...       ...     ...      ...
Y163O8161RUS       2   1600.00    Ford    Focus
M0309X197RUS       1  22300.00    Ford    Focus
O673E8197RUS       2    600.00    Ford    Focus
8610T8154RUS       1   2000.00    Ford    Focus
H419XE197RUS       2   8594.59  Toyota  Corolla

[593 rows x 4 columns]

* display the rows only where the __car number__ is from the list: [’Y7689C197RUS’, ’92928M178RUS’, ’7788KT197RUS’, ’H115YO163RUS’, ’X758HY197RUS’]

In [7]:
car_list = ["Y7689C197RUS", "92928M178RUS", "7788KT197RUS", "H115YO163RUS", "X758HY197RUS"]
display(df[df.index.isin(car_list)])  # колонка CarNumber - индекс

              Refund      Fines  Make  Model
CarNumber
92928M178RUS       1    8594.59  Ford  Focus
H115YO163RUS       1    2200.00  Ford  Focus
7788KT197RUS       2   12000.00  Ford  Focus
X758HY197RUS       2   24200.00  Ford  Focus
X758HY197RUS       2   72600.00  Ford  Focus
Y7689C197RUS       1   27000.00  Ford  Focus
92928M178RUS       1     600.00  Ford  Focus
H115YO163RUS       1    8594.59  Ford  Focus
H115YO163RUS       2    1100.00  Ford  Focus
7788KT197RUS       2    8594.59  Ford  Focus
7788KT197RUS       1   20000.00  Ford  Focus
X758HY197RUS       2  145200.00  Ford  Focus
92928M178RUS       1    1200.00  Ford  Focus
Y7689C197RUS       2    9000.00  Ford  Focus
Y7689C197RUS       2   45000.00  Ford  Focus
7788KT197RUS       2    4000.00  Ford  Focus
Y7689C197RUS       1   36000.00  Ford  Focus
92928M178RUS       2    3000.00  Ford  Focus

## 3) Make the aggregations with the make and the model

* display the median __fines__ grouped by the __make__

In [8]:
display(df.groupby(by="Make")["Fines"].median())

Make
Audi          4200.0
BMW           6500.0
Ford          3500.0
Skoda         3250.0
Toyota        7700.0
Volkswagen    4300.0
Volvo         8500.0
Name: Fines, dtype: float64

* display the median __fines__ grouped by the __make__ and __the model__

In [9]:
display(df.groupby(["Make", "Model"])["Fines"].median())

Make        Model
Ford        Focus      3500.0
            Mondeo     7650.0
Skoda       Octavia    3250.0
Toyota      Camry      7700.0
            Corolla    7700.0
Volkswagen  Golf       4800.0
            Jetta      2800.0
            Passat     3500.0
            Touareg    5800.0
Name: Fines, dtype: float64

* display the number of __fines__ grouped by the __make__ and the __model__ in order to understand if we can trust the median values

In [10]:
display(df.groupby(["Make", "Model"])["Fines"].count())

Make        Model
Ford        Focus      575
            Mondeo       6
Skoda       Octavia     48
Toyota      Camry       16
            Corolla     18
Volkswagen  Golf        20
            Jetta        6
            Passat      22
            Touareg      5
Name: Fines, dtype: int64

* display the minimum and the maximum __fines__ grouped by the __make__ and the __model__ in order to better understand the variance

In [11]:
display(df.groupby(["Make", "Model"])["Fines"].min())

Make        Model
Ford        Focus       100.0
            Mondeo     1100.0
Skoda       Octavia     300.0
Toyota      Camry       500.0
            Corolla     900.0
Volkswagen  Golf        200.0
            Jetta       500.0
            Passat      100.0
            Touareg     500.0
Name: Fines, dtype: float64

In [12]:
display(df.groupby(["Make", "Model"])["Fines"].max())

Make        Model
Ford        Focus      180000.00
            Mondeo      46200.00
Skoda       Octavia    145000.00
Toyota      Camry       22400.00
            Corolla     34300.00
Volkswagen  Golf       168000.00
            Jetta       46000.00
            Passat      29700.00
            Touareg      8594.59
Name: Fines, dtype: float64

или же одной строчкой:

In [13]:
display(df.groupby(by=["Make", "Model"]).aggregate({"Fines":["min", "max"]}))

                     Fines
                       min        max
Make       Model
Ford       Focus     100.0  180000.00
           Mondeo   1100.0   46200.00
Skoda      Octavia   300.0  145000.00
Toyota     Camry     500.0   22400.00
           Corolla   900.0   34300.00
Volkswagen Golf      200.0  168000.00
           Jetta     500.0   46000.00
           Passat    100.0   29700.00
           Touareg   500.0    8594.59

* display the standard deviation of the __fines__ grouped by the __make__ and the __model__ in order to better understand the variance

In [14]:
display(df.groupby(by=["Make", "Model"])["Fines"].std())

Make        Model
Ford        Focus      15041.269445
            Mondeo     18987.329108
Skoda       Octavia    24339.742131
Toyota      Camry       6410.250680
            Corolla     9629.325574
Volkswagen  Golf       36950.839914
            Jetta      17743.026799
            Passat      6969.739243
            Touareg     3461.779218
Name: Fines, dtype: float64

## 4) Make the aggregations with the car number

* display the __car numbers__ grouped by the __number of the fines__ in _descending order_, we want to find those who most often violated the law

In [15]:
display(df.groupby(by="CarNumber").aggregate({"Fines":["count"]}).sort_values(by=("Fines", "count"), ascending=False))

             Fines
             count
CarNumber
Y7689C197RUS     4
92928M178RUS     4
7788KT197RUS     4
H115YO163RUS     3
X758HY197RUS     3
...            ...
E42577152RUS     1
E42377152RUS     1
E41977152RUS     1
E41577152RUS     1
H917TC36RUS      1

[531 rows x 1 columns]

* select from the initial dataframe all the rows corresponding to the top-1 car number, we want to zoom in a little bit

In [32]:
grouped = df.groupby(by="CarNumber").aggregate({"Fines":["count"]}).sort_values(by=("Fines", "count"), ascending=False)
topCar = grouped.index[0]
display(df[df.index == topCar])

              Refund    Fines  Make  Model
CarNumber
Y7689C197RUS       1  27000.0  Ford  Focus
Y7689C197RUS       2   9000.0  Ford  Focus
Y7689C197RUS       2  45000.0  Ford  Focus
Y7689C197RUS       1  36000.0  Ford  Focus

* display the car numbers grouped by the sum of the __fines__ in _descending order_, we want to find those who paid the most

In [ ]:
display(df.groupby(by="CarNumber").aggregate(func={"Fines":["sum"]}).sort_values(by=("Fines", "sum"), ascending=False))

                 Fines
                   sum
CarNumber
X758HY197RUS  242000.0
9020YC197RUS  217500.0
M0279X197RUS  216000.0
Y352O8197RUS  207200.0
Y778EE197RUS  192000.0
...                ...
83218C154RUS     100.0
Y195O8161RUS     100.0
K376HE161RUS     100.0
705787163RUS     100.0
K326T8197RUS     100.0

[531 rows x 1 columns]

* select from the initial dataframe all the rows corresponding to the top-1 car number, we want to zoom in a little bit

In [31]:
g = df.groupby(by="CarNumber").aggregate(func={"Fines":["sum"]}).sort_values(by=("Fines", "sum"), ascending=False)
top_car = g.index[0]
display(df[df.index == top_car])

              Refund     Fines  Make  Model
CarNumber
X758HY197RUS       2   24200.0  Ford  Focus
X758HY197RUS       2   72600.0  Ford  Focus
X758HY197RUS       2  145200.0  Ford  Focus

* display a table that answers the question: are there any car numbers that were connected to different models?

In [39]:
res = df.groupby(by=["CarNumber", "Model"]).aggregate(func={"Model":["nunique"]}).sort_values(by=("Model","nunique"), ascending=False)
display(res)
print("Видно, что у всех номеров только 1 модель")

                       Model
                     nunique
CarNumber    Model
704687163RUS Focus         1
O752MX161RUS Focus         1
O718MM163RUS Focus         1
O6939X163RUS Focus         1
O68897197RUS Focus         1
...                      ...
9975CC77RUS  Focus         1
9943OH154RUS Octavia       1
9943KK197RUS Focus         1
9942KK197RUS Focus         1
Y973O8197RUS Focus         1

[524 rows x 1 columns]

Видно, что у всех номеров только 1 модель