# Quest 5

In [2]:
import pandas as pd
import gc

## 1) Read the fines.csv that you saved in the previous exercise

In [3]:
df = pd.read_csv("../ex04/fines.csv")
display(df)

            CarNumber  Refund    Fines        Make   Model  Year
0        Y163O8161RUS       2   3200.0        Ford   Focus  1989
1         E432XX77RUS       1   6500.0      Toyota   Camry  1995
2         7184TT36RUS       1   2100.0        Ford   Focus  1984
3        X582HE161RUS       2   2000.0        Ford   Focus  2015
4        92918M178RUS       1   5700.0        Ford   Focus  2014
..                ...     ...      ...         ...     ...   ...
925    I837GX83923RUS       1  21000.0      Toyota   Focus  1999
926     X777XX7777RUS       2   3000.0  Volkswagen   Focus  2000
927  T834DJ9384734RUS       1   1500.0      Toyota   Camry  1998
928      X000Q0000RUS       2  40000.0        Ford  Passat  2004
929     89384CC374RUS       1   1000.0      Toyota   Camry  2025

[930 rows x 6 columns]

## 2) Iterations

Сalculate __fines/refund*year__ for each row and create a new column with the calculated data and measure the time using the magic command %%timeit in the cell

### 1. Loop

In [4]:
def calculate_rows():
    values = []
    for i in range(len(df)):
        fines = df.iloc[i, 2]   # iloc не считывает индексы
        refund = df.iloc[i, 1]
        year = df.iloc[i, 5]
        values.append(fines/refund*year)
    return values

In [ ]:
%%timeit 
df["Res Loop"] = calculate_rows()

###  2. Iterrows()

In [ ]:
def calculate_iter():
    values = []
    for index, row in df.iterrows():
        fines = row["Fines"]
        refund = row["Refund"]
        year = row["Year"]
        values.append(fines/refund*year)
    return values

In [ ]:
%%timeit 
df["Res Iter"] = calculate_iter()

28.3 ms ± 86.1 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

### 3. Apply() and lambda function

In [ ]:
%%timeit
df["Res Lambda"] = df.apply(lambda row: row["Fines"] / row["Refund"] * row["Year"], axis=1)  # приметить функцию построчно

9.6 ms ± 13.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

### 4. Series objects from the dataframe

In [ ]:
%%timeit
df["Res Series"] = df["Fines"] / df["Refund"] * df["Year"]

193 µs ± 1.09 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

### 5. .values

In [ ]:
%%timeit
df["Res Values"] = df["Fines"].values / df["Refund"].values * df["Year"].values

92.4 µs ± 68.2 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

В итоге по эффективности получилось:
1) apply() + lambda
2) itterrows()
2) loop
3) series + .values
4) series

In [ ]:
display(df)

,CarNumber,Refund,Fines,Make,Model,Year,Res Loop,Res Iter,Res Lambda,Res Series,Res Values
0,Y163O8161RUS,2,3200.0,Ford,Focus,1989,3182400.0,3182400.0,3182400.0,3182400.0,3182400.0
1,E432XX77RUS,1,6500.0,Toyota,Camry,1995,12967500.0,12967500.0,12967500.0,12967500.0,12967500.0
2,7184TT36RUS,1,2100.0,Ford,Focus,1984,4166400.0,4166400.0,4166400.0,4166400.0,4166400.0
3,X582HE161RUS,2,2000.0,Ford,Focus,2015,2015000.0,2015000.0,2015000.0,2015000.0,2015000.0
4,92918M178RUS,1,5700.0,Ford,Focus,2014,11479800.0,11479800.0,11479800.0,11479800.0,11479800.0
...,...,...,...,...,...,...,...,...,...,...,...
925,I837GX83923RUS,1,21000.0,Toyota,Focus,1999,41979000.0,41979000.0,41979000.0,41979000.0,41979000.0
926,X777XX7777RUS,2,3000.0,Volkswagen,Focus,2000,3000000.0,3000000.0,3000000.0,3000000.0,3000000.0
927,T834DJ9384734RUS,1,1500.0,Toyota,Camry,1998,2997000.0,2997000.0,2997000.0,2997000.0,2997000.0
928,X000Q0000RUS,2,40000.0,Ford,Passat,2004,40080000.0,40080000.0,40080000.0,40080000.0,40080000.0
929,89384CC374RUS,1,1000.0,Toyota,Camry,2025,2025000.0,2025000.0,2025000.0,2025000.0,2025000.0

## 3) Indexing: measure the time using the magic command %%timeit in the cell

* get a row for a specific CarNumber, for example, ’O136HO197RUS’

In [ ]:
car_to_find = "O136HO197RUS"

In [ ]:
%%timeit
new_df = df[df["CarNumber"] == car_to_find]

186 µs ± 546 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

* set the index in your dataframe with CarNumber

In [ ]:

df.set_index("CarNumber", inplace=True)

In [ ]:

display(df)

,Refund,Fines,Make,Model,Year,Res Loop,Res Iter,Res Lambda,Res Series,Res Values
CarNumber,,,,,,,,,,
Y163O8161RUS,2,3200.0,Ford,Focus,1989,3182400.0,3182400.0,3182400.0,3182400.0,3182400.0
E432XX77RUS,1,6500.0,Toyota,Camry,1995,12967500.0,12967500.0,12967500.0,12967500.0,12967500.0
7184TT36RUS,1,2100.0,Ford,Focus,1984,4166400.0,4166400.0,4166400.0,4166400.0,4166400.0
X582HE161RUS,2,2000.0,Ford,Focus,2015,2015000.0,2015000.0,2015000.0,2015000.0,2015000.0
92918M178RUS,1,5700.0,Ford,Focus,2014,11479800.0,11479800.0,11479800.0,11479800.0,11479800.0
...,...,...,...,...,...,...,...,...,...,...
I837GX83923RUS,1,21000.0,Toyota,Focus,1999,41979000.0,41979000.0,41979000.0,41979000.0,41979000.0
X777XX7777RUS,2,3000.0,Volkswagen,Focus,2000,3000000.0,3000000.0,3000000.0,3000000.0,3000000.0
T834DJ9384734RUS,1,1500.0,Toyota,Camry,1998,2997000.0,2997000.0,2997000.0,2997000.0,2997000.0
X000Q0000RUS,2,40000.0,Ford,Passat,2004,40080000.0,40080000.0,40080000.0,40080000.0,40080000.0
89384CC374RUS,1,1000.0,Toyota,Camry,2025,2025000.0,2025000.0,2025000.0,2025000.0,2025000.0

* again, get a row for the same CarNumber

In [ ]:
display(df[df.index == car_to_find])

,Refund,Fines,Make,Model,Year,Res Loop,Res Iter,Res Lambda,Res Series,Res Values
CarNumber,,,,,,,,,,
O136HO197RUS,2,7800.0,Toyota,Corolla,1989,7757100.0,7757100.0,7757100.0,7757100.0,7757100.0
O136HO197RUS,2,1300.0,Toyota,Corolla,1997,1298050.0,1298050.0,1298050.0,1298050.0,1298050.0

## 5) Downcasting

* Run df.info(memory_usage=’deep’), pay attention to the Dtype and the memory usage

In [ ]:
df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
Index: 930 entries, Y163O8161RUS to 89384CC374RUS
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Refund      930 non-null    int64
 1   Fines       930 non-null    float64
 2   Make        930 non-null    object
 3   Model       919 non-null    object
 4   Year        930 non-null    int64
 5   Res Loop    930 non-null    float64
 6   Res Iter    930 non-null    float64
 7   Res Lambda  930 non-null    float64
 8   Res Series  930 non-null    float64
 9   Res Values  930 non-null    float64
dtypes: float64(6), int64(2), object(2)
memory usage: 232.8 KB

In [ ]:
display(df)

,Refund,Fines,Make,Model,Year,Res Loop,Res Iter,Res Lambda,Res Series,Res Values
CarNumber,,,,,,,,,,
Y163O8161RUS,2,3200.0,Ford,Focus,1989,3182400.0,3182400.0,3182400.0,3182400.0,3182400.0
E432XX77RUS,1,6500.0,Toyota,Camry,1995,12967500.0,12967500.0,12967500.0,12967500.0,12967500.0
7184TT36RUS,1,2100.0,Ford,Focus,1984,4166400.0,4166400.0,4166400.0,4166400.0,4166400.0
X582HE161RUS,2,2000.0,Ford,Focus,2015,2015000.0,2015000.0,2015000.0,2015000.0,2015000.0
92918M178RUS,1,5700.0,Ford,Focus,2014,11479800.0,11479800.0,11479800.0,11479800.0,11479800.0
...,...,...,...,...,...,...,...,...,...,...
I837GX83923RUS,1,21000.0,Toyota,Focus,1999,41979000.0,41979000.0,41979000.0,41979000.0,41979000.0
X777XX7777RUS,2,3000.0,Volkswagen,Focus,2000,3000000.0,3000000.0,3000000.0,3000000.0,3000000.0
T834DJ9384734RUS,1,1500.0,Toyota,Camry,1998,2997000.0,2997000.0,2997000.0,2997000.0,2997000.0
X000Q0000RUS,2,40000.0,Ford,Passat,2004,40080000.0,40080000.0,40080000.0,40080000.0,40080000.0
89384CC374RUS,1,1000.0,Toyota,Camry,2025,2025000.0,2025000.0,2025000.0,2025000.0,2025000.0

In [ ]:
df.dtypes

Refund          int64
Fines         float64
Make           object
Model          object
Year            int64
Res Loop      float64
Res Iter      float64
Res Lambda    float64
Res Series    float64
Res Values    float64
dtype: object

In [ ]:
opt_df = df.copy()

* make a copy() of your initial dataframe into another dataframe optimized

Проанализируем диапазон значений в численных колонках:

In [ ]:
for column in df.columns:
    try:
        print(f"|Колонка '{column}'| занчения от {opt_df[column].min()} до {opt_df[column].max()}")
    except (SyntaxError, TypeError):
        print(f"|Колонка '{column}'| не численное значение")

|Колонка 'Refund'| занчения от 1 до 2
|Колонка 'Fines'| занчения от 100.0 до 180000.0
|Колонка 'Make'| занчения от Audi до Volvo
|Колонка 'Model'| не численное значение
|Колонка 'Year'| занчения от 1980 до 2025
|Колонка 'Res Loop'| занчения от 99750.0 до 188376000.0
|Колонка 'Res Iter'| занчения от 99750.0 до 188376000.0
|Колонка 'Res Lambda'| занчения от 99750.0 до 188376000.0
|Колонка 'Res Series'| занчения от 99750.0 до 188376000.0
|Колонка 'Res Values'| занчения от 99750.0 до 188376000.0

В итоге:
1) Для колонки Refund: int64 (который вмещает от/до ± 9 223 372 036 854 775 807) -> uint8 (0;255) (8 байт -> 1 байт)
Результат: -6.3 KB

In [ ]:
opt_df["Refund"] = opt_df["Refund"].astype("uint8")
opt_df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
Index: 930 entries, Y163O8161RUS to 89384CC374RUS
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Refund      930 non-null    uint8
 1   Fines       930 non-null    float64
 2   Make        930 non-null    object
 3   Model       919 non-null    object
 4   Year        930 non-null    int64
 5   Res Loop    930 non-null    float64
 6   Res Iter    930 non-null    float64
 7   Res Lambda  930 non-null    float64
 8   Res Series  930 non-null    float64
 9   Res Values  930 non-null    float64
dtypes: float64(6), int64(1), object(2), uint8(1)
memory usage: 226.4 KB

2) Колонка "Fines" float64 (±1.79e+308) -> float32 (±3.40E+38) (8 байт -> 4 байта)
Результат: - 3.7 KB

In [ ]:
opt_df["Fines"] = opt_df["Fines"].astype("float32")
opt_df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
Index: 930 entries, Y163O8161RUS to 89384CC374RUS
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Refund      930 non-null    uint8
 1   Fines       930 non-null    float32
 2   Make        930 non-null    object
 3   Model       919 non-null    object
 4   Year        930 non-null    int64
 5   Res Loop    930 non-null    float64
 6   Res Iter    930 non-null    float64
 7   Res Lambda  930 non-null    float64
 8   Res Series  930 non-null    float64
 9   Res Values  930 non-null    float64
dtypes: float32(1), float64(5), int64(1), object(2), uint8(1)
memory usage: 222.8 KB

3) Колонки Make и Model: определим точный тип
Результат: - 8.7 KB

In [ ]:
opt_df['Make'] = opt_df['Make'].astype('category')
opt_df['Model'] = opt_df['Model'].astype('category')
opt_df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
Index: 930 entries, Y163O8161RUS to 89384CC374RUS
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Refund      930 non-null    uint8
 1   Fines       930 non-null    float32
 2   Make        930 non-null    category
 3   Model       919 non-null    category
 4   Year        930 non-null    int64
 5   Res Loop    930 non-null    float64
 6   Res Iter    930 non-null    float64
 7   Res Lambda  930 non-null    float64
 8   Res Series  930 non-null    float64
 9   Res Values  930 non-null    float64
dtypes: category(2), float32(1), float64(5), int64(1), uint8(1)
memory usage: 114.0 KB

4. Аналогично для колонок Year, Res:

In [ ]:
opt_df["Year"] = opt_df["Year"].astype("int16")
opt_df["Res Loop"] = opt_df["Res Loop"].astype("float32")
opt_df["Res Iter"] = opt_df["Res Iter"].astype("float32")
opt_df["Res Lambda"] = opt_df["Res Lambda"].astype("float32")
opt_df["Res Series"] = opt_df["Res Series"].astype("float32")
opt_df["Res Values"] = opt_df["Res Values"].astype("float32")
opt_df.index = opt_df.index.astype("category")

In [ ]:
df.info(memory_usage="deep")
opt_df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
Index: 930 entries, Y163O8161RUS to 89384CC374RUS
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Refund      930 non-null    int64
 1   Fines       930 non-null    float64
 2   Make        930 non-null    object
 3   Model       919 non-null    object
 4   Year        930 non-null    int64
 5   Res Loop    930 non-null    float64
 6   Res Iter    930 non-null    float64
 7   Res Lambda  930 non-null    float64
 8   Res Series  930 non-null    float64
 9   Res Values  930 non-null    float64
dtypes: float64(6), int64(2), object(2)
memory usage: 232.8 KB
<class 'pandas.core.frame.DataFrame'>
CategoricalIndex: 930 entries, Y163O8161RUS to 89384CC374RUS
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Refund      930 non-null    uint8
 1   Fines       930 non-null    float32
 2   Make        930 non-null    category
 3   Model       919 non-null    category
 4   Year        930 non-null    int16
 5   Res Loop    930 non-null    float32
 6   Res Iter    930 non-null    float32
 7   Res Lambda  930 non-null    float32
 8   Res Series  930 non-null    float32
 9   Res Values  930 non-null    float32
dtypes: category(2), float32(6), int16(1), uint8(1)
memory usage: 81.9 KB

Отдельно выведим типы индексов:

In [ ]:
print(df.index.dtype)

object

In [ ]:
print(opt_df.index.dtype)

category

Как видно, оптимазация - 142.4 KB ≈ 61% от первоначальной таблицы

Удалим исходную таблицу df:

In [ ]:
gc.enable()
%reset_selective df
del df
gc.collect()
print(df)

Nothing done.

NameError: name 'df' is not defined

Видно, что переменная df была удалена.